version: '3.9'
services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=phoenix_development
      - POSTGRES_PASSWORD=""
      - POSTGRES_HOST_AUTH_METHOD=trust
    container_name: db
    hostname: db
    ports:
      - '5432:5432'
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 1s
    volumes:
      # Will use db volume and inside to path /var/lib/mysql
      - ./tmp/db/postgresql/data:/var/lib/postgresql/data
    networks:
      - dbs
  elasticsearch:
    image: hypothesis/elasticsearch:latest
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
    networks:
      - elasticsearch
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - es_logs:/usr/share/elasticsearch/logs
      - es_config:/usr/share/elasticsearch/config
  ota:
    image: pondersource/tosdr-ota:1.3
    ports:
      - '127.0.0.1:4000:3000'
    networks:
      - dbs
    environment:
      - API_SECRET=foo
    cap_add: [ SYS_ADMIN ]
  web:
    tty: true
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    ports:
      - 9090:3000
    depends_on:
      - db
      - elasticsearch
    volumes:
      - ./app:/usr/src/edit.tosdr.org/app/
      - ./lib:/usr/src/edit.tosdr.org/lib/
      - ./db:/usr/src/edit.tosdr.org/db/
      - ./config:/usr/src/edit.tosdr.org/config/
      - ./spec:/usr/src/edit.tosdr.org/spec/
    networks:
      - dbs
      - elasticsearch
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=""
      - DATABASE_NAME=phoenix_development
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - H_ORIGIN=http://localhost:5000
      - WEB_PORT=9090
      - ELASTICSEARCH_HOST=elasticsearch
      - AUTHORITY=localhost
      - OTA_URL=
      - OTA_API_SECRET=
      - DOCBOT_USER=docbot
  adminer:
    image: adminer
    ports:
      - 1337:8080
    environment:
      - RAILS_ENV=development

volumes:
  # Create volume called web for persistent storage
  web:
    # Specify name so it does not append stack name
    name: web
  es_data:
    driver: local
  es_logs:
    driver: local
  es_config:
    driver: local
networks:
  dbs:
    # Joins existing network of this name (it was created by db container)
    external: true
    # Specify name so that it does not append stack name
    name: dbs
  elasticsearch:
    external: true
    name: elasticsearch
  engine:
    external: true
    name: engine
